

DROP TABLE "SCOTT"."MOVIE_HAS_GENRE";
DROP TABLE "SCOTT"."GENRE";
DROP TABLE "SCOTT"."MOVIE";
DROP TABLE "SCOTT"."DIRECTOR";


CREATE TABLE "SCOTT"."GENRE" (
	"ID" NUMBER(3) NOT NULL PRIMARY KEY,
	"NAME" VARCHAR2(20) NOT NULL
);
CREATE TABLE "SCOTT"."DIRECTOR" (
	"ID" NUMBER(3) NOT NULL PRIMARY KEY,
	"FIRST_NAME" VARCHAR2(20),
	"MID_NAME" VARCHAR2(20),
	"LAST_NAME" VARCHAR2(20) NOT NULL,
	"ABOUT" VARCHAR2(255)
);
CREATE TABLE "SCOTT"."MOVIE" (
	"ID" NUMBER(3) NOT NULL PRIMARY KEY,
	"TITLE" VARCHAR2(100),
	"DIRECTOR_ID" NUMBER(3),
	"RELEASE_YEAR" NUMBER(4,0),
	"RATING" NUMBER(2,1),
	"ABOUT" VARCHAR2(2000)
);
ALTER TABLE "SCOTT"."MOVIE" ADD FOREIGN KEY ("DIRECTOR_ID") REFERENCES "SCOTT"."DIRECTOR" ("ID");
CREATE TABLE "SCOTT"."MOVIE_HAS_GENRE" (
	"MOVIE_ID" NUMBER(3,0) NOT NULL,
	"GENRE_ID" NUMBER(3,0) NOT NULL
);
ALTER TABLE "SCOTT"."MOVIE_HAS_GENRE" ADD FOREIGN KEY ("MOVIE_ID") REFERENCES "SCOTT"."MOVIE" ("ID");
ALTER TABLE "SCOTT"."MOVIE_HAS_GENRE" ADD FOREIGN KEY ("GENRE_ID") REFERENCES "SCOTT"."GENRE" ("ID");
